name: my-lando-app
excludes:
  - node_modules
  - dist
  - .git
services:
  angular:
    type: node:22
    globals:
      gulp-cli: latest
    build_as_root:
      - apt update
      - apt install -y chromium
    build:
      - npm install -g npm@11.3.0
      - npm install
    command: npm run start
    port: 4200
    ssl: 4443
    overrides:
      hostname: angular
      working_dir: /app
      environment:
        - CHROME_BIN=/usr/bin/chromium
      volumes:
        - ./angular-app:/app
        - .prettierrc:/app/.prettierrc
        - .prettierignore:/app/.prettierignore

  nestjs:
    type: node:22
    build:
      - npm install -g npm@11.3.0
      - npm install
      - npx prisma migrate deploy
      - npx prisma generate
      #- npx prisma db seed
    command: npm run start:dev
    port: 3000
    ssl: 4443
    overrides:
      hostname: nestjs
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@postgres/myapp?schema=public
        - NODE_ENV=development
      volumes:
        - ./nestjs-app:/app
        - .prettierrc:/app/.prettierrc
        - .prettierignore:/app/.prettierignore
      depends_on:
        - postgres

  postgres:
    type: postgres
    creds:
      user: postgres
      password: postgres
      database: myapp

  redis:
    type: redis
    persist: true

  mailhog:
    type: mailhog
    ssl: true

proxy:
  angular:
    - myapp.local:4200
  nestjs:
    - api.myapp.local:3000
  mailhog:
    - mail.myapp.local

tooling:
  psql:
    service: postgres
  format:
    description: Run formatters
    cmd:
      - angular: npm run format
      - nestjs: npm run format
  lint:
    description: Run linters
    cmd:
      - angular: npm run lint
      - nestjs: npm run lint
  type-check:
    desicription: Run type checking
    cmd:
      - angular: npm run type-check
      - nestjs: npm run type-check
  prisma-validate:
    description: Validate the Prisma schema
    service: nestjs
    cmd: npx prisma validate
  test:
    description: Run all the tests
    cmd:
      - angular: npm run test
      - nestjs: npm run test && npm run test:e2e && npm run test:cov
  build:
    description: Build the apps
    cmd:
      - angular: npm run build
      - nestjs: npm run build
